### ISSUE TITLE
unable to get goka running with the following error. 

### ISSUE THREAD

**Issue by shubham7saxena** [lovoo/goka#119]
Error creating processor: topic group-1-table has 50 partitions instead of 400 exit status 1

I see that this configuration comes from sarama. any particular reason I could be facing this.

**Comment by db7** [comment]
The error is saying that your group-table has only 50 partitions (perhaps the default of your Kafka configuration if you have `auto.create.topics.enable=true`?) instead of the 400 partitions that your input streams have. Perhaps we should make the error message a bit more informative.

In goka, the input topics, joined tables and group tables have to have the same number of partitions (be copartitioned). You can output, of course, into topics with different number of partitions than the input.

Regarding your group table, you have two options: either you create the group table by hand with the same number of partitions as the input streams, or you let goka create for you by passing a zookeeper-based topic manager as option. Perhaps the [wiki page](https://github.com/lovoo/goka/wiki/Tips#configuring-log-compaction-for-table-topics) can help you further.

**Comment by db7** [comment]
@shubham7saxena any updates on this issue?

**Comment by db7** [comment]
I'm assuming this problem is not relevant anymore. Please reopen if needed.
