### ISSUE TITLE
review errors to fail on

### ISSUE THREAD

**Issue by frairon** [lovoo/goka#140]
When loading a view and kafka gives the message
"response did not contain all the expected topic/partition blocks",
goka should tolerate the message and just keep going.
According to the linked issue, this is normal behavior.

https://github.com/Shopify/sarama/issues/1087

**Comment by frairon** [comment]
error fixed in new sarama version

**Comment by db7** [comment]
@annymsMthd Good to know, thank you! 

We stopped our migration to Kafka 1.0 a year ago because of this error. I was hoping it was already fixed by now.

As far as I remember the issue does not occur with Confluent's library. If you'd like to try, we have a wrapper for it here: https://github.com/lovoo/goka/tree/master/kafka/confluent.
