### ISSUE TITLE
Question: Scanning a Joined Topic

### ISSUE THREAD

**Issue by CatalystG** [lovoo/goka#159]
I'm trying to see if a particular pattern would work with Goka or if it would be better done in a separate service with a more traditional database. I was wondering if you had any experience with trying to solve a problem like this with Kafka and Goka:

There are two topics, topic-1 and topic-2.

- topic-1 is a large group table, something like users, keyed off a userID with a value that contains a number of attributes associated with the user for example role (Admin, Developer, etc.), Department and others.
- topic-2 has settings that we want to associate either directly to a userID, or to all users in a role, Department or some combination of those and is less likely to grow. It would be keyed off a unique ID.

The goal would be to have an output topic that enriches topic-1 with the list of applicable settings from topic-2.

I can't seem to come up with a way to get this to work. A few of the ideas that don't seem to work: 

1. One thought was to allow Iterator-like scanning of the View generated by a Lookup edge of topic-2 to find all applicable settings that match a change to topic-1. You would also need to handle changes to topic-2 but that would require a similar scan of topic-1 which doesn't seem feasible.

2. Attempt to either use loopback or a separate processor to fan out topic-2 so it is keyed off userID and aggregates all applicable settings then join that back to topic-1. I think that would work but I can't see how this re-keyed topic would be generated in Goka. I could see a separate service using something like Kafka Connect with Postgres working to occasionally reconcile this re-keyed topic but that adds a lot of complexity.

Any thoughts?

**Comment by db7** [comment]
@CatalystG you are right, there is no direct way how to implement that. Here are some thoughts.

If you *could* join both tables using only the userID, then you could subscribe for the table updates as if they were streams and join them in a new group table. That would update the joined topic whenever any of the input tables is changed.

Since you cannot join the tables only using the userID, you could create a View of the small table (not a Lookup edge). Then create a processor with input stream being the large table and pass the view to the ProcessCallback, so that you can iterate over the small table whenever the large table is updated.
The issue here is that the small table does not trigger updates of the joined topic.

If you cannot give up on that, the only relatively clean (but not scalable way) how to do what you want is the following. You create two views (no processors) and add UpdateCallbacks to the views with the option `WithViewCallback`. In the callbacks you iterate over the non-modified table and compare it with the modified value of the other table. If they match then you emit an update with an emitter.

Here is some example code that won't compile and doesn't handle any errors.
```go
var (
  small *goka.View
  large *goka.View
)

// create an emitter to update the output topic
emitter, _ := goka.NewEmitter(outputTopic, codec)
defer emitter.Finish()

// create a callback for settings updates
upSettings := func(s storage.Storage, p int32, k string, v []byte) error {
  // first update the local storage as a normal view would do
  if err := goka.DefaultUpdate(s, p, k, v); err != nil {
    return err
  }
  // get updated settings
  settings, _ := small.Get(k)
  // iterate over the users table
  it, _ := large.Iterator()
  for it.Next() {
    // if the user match the settings
    if match(it.Value(), settings) {
      // emit the joined value into output Topic (key is userID)
      emitter.Emit(it.Key(), join(it.Value(), settings))
    }
  }
  return nil
}

// now create a callback for user updates
upUsers := func(s storage.Storage, p int32, k string, v []byte) error {
  // first update the local storage as a normal view would do
  if err := goka.DefaultUpdate(s, p, k, v); err != nil {
    return err
  }
  // get updated user
  user, _ := large.Get(k)
  // iterate over the settings table
  it, _ := small.Iterator()
  for it.Next() {
    // if the user match the settings
    if match(user, it.Value()) {
      // emit the joined value into output Topic (key is userID)
      emitter.Emit(k, join(user, it.Value()))
    }
  }
  return nil
}

small, _ := goka.NewView(smallTable, codec, goka.WithViewCallback(upSettings))
large, _ := goka.NewView(largeTable, codec, goka.WithViewCallback(upUsers))

// start views
...
```

This program cannot run partitioned, so you'll need a machine that is fat enough.

Let me know if that helps.

**Comment by CatalystG** [comment]
Thanks a lot, that is a big help. Using views as inputs to processors and using views directly with callbacks are interesting patterns I hadn't thought of that might help with some other things I was looking at. 

Knowing there isn't a clean way to have it work partitioned and scalable means it's probably worth it to explore other options to at least generate the fanned out UserId->Settings topic that isn't bound to a single node.

**Comment by db7** [comment]
@CatalystG, I'll close this ticket. From your previous reply, I understood that your issue has been answered. If not, please reopen the ticket!
