### ISSUE TITLE
Question: Why use goka over plain Sarama ?

### ISSUE THREAD

**Issue by prune998** [lovoo/goka#168]
I don't really see the point in goka over Sarama, which is used for the Kafka communication anyway ?

goka seem only to ease the use of emitters/receivers instead of some `for` loops with `channels`... 
What would be the arguments to re-write my 20 micro-services using sarama / saramacluster to use goka ? 
Would goka be more efficient ?

I don't mean to be rude, i'm just quick checking to understand is goka is better overall or just easier for new projects ?

**Comment by db7** [comment]
Goka is about state. If you don't have state, Goka is probably not the right library for you.

Goka provides components to help you to build *stateful* systems that react to input streams with low latency and can scale. If you need to aggregate a stream or build a stateful system, Goka takes care of keeping your state safe inside Kafka -- you won't need to connect to another system and think about scaling the storage or about replicating the storage since Kafka gives you these features already. Having the state in Kafka also allows you to compose systems by observing the state of each other. That is really powerful. Perhaps this [Goka introduction](https://github.com/lovoo/goka/wiki/Introduction) can be helpful.

That said, if you already have your 20 microservices built with Sarama and you handle your state properly, I don't see why you should rewrite them with Goka. And I don't know if they would be more efficient with Goka. It depends on how you handle your state.

Hope that helped.

If you'd like to try Goka and need help to get started, let me know.

**Comment by frairon** [comment]
Closing the issue as the question seems to be answered. Feel free to reopen if something is still unclear.
