### ISSUE TITLE
Emitter emits messages to one partition

### ISSUE THREAD

**Issue by 5cmpersec** [lovoo/goka#171]
```go
ctx, cancel := context.WithCancel(context.Background())
...
ctx.Emit(output_topic, ctx.Key(), msg)
```

We expect that when `ctx.Key()` is empty, output messages should be uniformly distributed across target partitions. However, all messages (from multiple app instances) go into only one partition.

**Comment by frairon** [comment]
Hi 5cmpersec,

Emitting a message in Goka (inside the processor-callback or using the Emitter) uses a sarama.AsyncProducer under the hood. Partitioning is configured when creating that producer, and per default Goka uses a partitioner, which (as far as I can see), makes nil-messages go into a random partition.
So I suppose your case is `key == ""` instead of `key == nil` when all messages end up in the same partition. If you want to avoid implementing a custom Partitioner, an easy workaround is to check if the key is empty and replace it with `nil` when emitting. If you do need round-robin-behavior for empty keys, you're going to have to implement that. But it's not hard.

When creating the processor, just pass the option `goka.WithProducerBuilder`, providing a producerbuilder (start with the default one [here](https://github.com/lovoo/goka/blob/master/kafka/builders.go) and modify it to use a different Partitioner.

Be careful though, because the ProducerBuilder is also used for storing the Group-Table in Kafka. So using a raw RoundRobinPartitioner or RandomPartioner will mess up your state. Instead you'll probably want to use a CustomPartitionerr that does key-based partitioning per default and only falls back to RoundRobin when the key is empty (or nil). Take a look at the sources of Shopify's producer implementations.. they're pretty self-explanatory.

Hope that helps, let us know if you're still having issues.

**Comment by frairon** [comment]
@5cmpersec assuming the question is answered I'll close the issue. If there are still unclear points, let me know.

**Comment by 5cmpersec** [comment]
@frairon Thank you
I implemented a custom Partitioner and it works as expected.

**Comment by activeshadow** [comment]
@frairon I'm seeing a similar issue, even when the keys used when emitting a message are non-nil and different. As an example, I have a processor that's part of a processor group that subscribes to the same topic that I then scale in Kubernetes. The topic being subscribed to has 3 partitions, and I have 3 processors running within the group (so presumably each processor instance gets assigned to a different partition). Looking at logs, only a single processor instance is processing all the messages, making me think all the messages are being emitted to the same partition, regardless of the key.

Thoughts? I'm sure I'm doing something wrong...

**Comment by activeshadow** [comment]
@frairon I don't mean to be annoying, but I really can't figure out the issue here and it's one of the last things keeping me from being able to use `goka` in production.

Any thoughts?

**Comment by abhishekrb19** [comment]
@activeshadow , are we sure that the partition rebalance (new kafka assignment) happens after new instances are added?

Also, I think new support was added recently to support rebalance callbacks (with https://github.com/lovoo/goka/pull/196) which should address your use case?

Alternatively, if you don't want dynamic rebalancing and you could do static partitioning (deterministically assign instance -> partition mapping).

You could also use tools such as tailer (https://github.com/lovoo/goka-tools/tree/master/tailer) to verify the last mesage/offsets on a given topic or write your own tool to see if the messages are all going to a single partition (which I don't think is the case).

**Comment by db7** [comment]
@activeshadow that sounds indeed weird, can you confirm that the other partitions are empty? Either with tailer or kafkacat?

**Comment by activeshadow** [comment]
@abhishekrb19 I'm not sure how to tell if the partition rebalance is happening... any hints? I would prefer dynamic rebalancing if at all possible.

@abhishekrb19 @db7 OK so I was incorrect instating that the other two partitions were empty... they are not. They are indeed getting written to.

After further investigation, based on your comments above, it looks to me like the first processor to come up gets all 3 partitions, and when the other two processors come up they aren't getting assigned to a partition. Sounds like a rebalancing issue? Am I not doing something in my code that I need to in order to cause the rebalance to happen? I make sure all my processors use the same processor group name.

**Comment by abhishekrb19** [comment]
@activeshadow, perhaps this log: https://github.com/lovoo/goka/blob/master/processor.go#L659?

```kafka-consumer-groups --bootstrap-server 0.0.0.0:9092 --execute --group <your_group> --describe```
would probably give some hint as well?

I am not sure when/how kafka partition rebalance gets invoked when a new client/instance for a group is added.

**Comment by frairon** [comment]
@kichel98, yeah you're right, emitting nil-key doesn't work, not really sure what was the context above - that was never an option :). 
Why would you want to use a nil-key in the first place?

**Comment by kichel98** [comment]
I want to use null keys because I want to let Kafka decide which partition should messages be sent to using its default partitioning strategy. I want messages to be optimally distributed to all partitions without implementing it on my own. AFAIK, null keys in messages are totally valid for Kafka and other Kafka clients and `goka` should not be an exception.

https://www.conduktor.io/kafka/producer-default-partitioner-and-sticky-partitioner/

**Comment by db7** [comment]
That was a conscious design decision to force the use of keys. You can always add a producer from Sarama to the function closure and emit null-key records. Perhaps one could add that option to the Emitter in goka, but I would suggest to keep the requirement of having non-null keys for the context operations.
