### ISSUE TITLE
Using a tester with an emitter doesn't seem to be working

### ISSUE THREAD

**Issue by activeshadow** [lovoo/goka#188]
Am I doing something wrong? The following test fails...

```
package emitme

import (
	"bytes"
	"io/ioutil"
	"log"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/lovoo/goka"
	"github.com/lovoo/goka/codec"
	"github.com/lovoo/goka/tester"
	"github.com/stretchr/testify/assert"
)

func handle(emitter *goka.Emitter) func(http.ResponseWriter, *http.Request) {
	return func(w http.ResponseWriter, r *http.Request) {
		body, err := ioutil.ReadAll(r.Body)
		if err != nil {
			w.WriteHeader(http.StatusBadRequest)
			return
		}

                log.Printf("emitting %s\n", string(body))

		if _, err := emitter.Emit("", body); err != nil {
			log.Printf("error emitting: %v", err)
			w.WriteHeader(http.StatusInternalServerError)
			return
		}

		w.WriteHeader(http.StatusNoContent)
	}
}

var job = []byte("hello, world!")

func TestEmitter(t *testing.T) {
	var gkt = tester.New(t)

	em, _ := goka.NewEmitter(nil, goka.Stream("test"), new(codec.Bytes), goka.WithEmitterTester(gkt))
	est := gkt.NewQueueTracker("test")

	r, _ := http.NewRequest("POST", "http://test.me/job", bytes.NewReader(job))
	w := httptest.NewRecorder()

	handle(em)(w, r)

	em.Finish()

	_, _, ok := est.Next()
	assert.True(t, ok)
}

```

Using the tester with a Goka Processor works with similar test code (ie. the return value of `est.Next()` is what I expect it to be). Does using the tester to provide topics for the Emitter to write to not work like it does with Processors, or am I just doing something wrong?

**Comment by frairon** [comment]
Hi Bryan,

thanks for reporting this, it turns out that this is indeed a bug in the tester code.

Let me give some background:
The tester basically keeps two levels of queues. One incoming queue and one that is pushed to the consumers (processors and views). Whenever we pass a message to the tester via `Consume`, the message is put into the incoming queue, then the tester waits until all consumers have processed the message and the messages they might have produced have been consumed etc.
We do this to synchronize the test to be sure, that when the `Consume`-method returns, all message created have been processed by all processors, since they're each in separate goroutines.
When a processor emits a new message while consuming a message, it will not pass that to the tester's `Consume`-function, because this would cause a dead-lock, instead it uses an internal method that puts the message on the incoming-queue.
The emitter behaves the same. It does not put the message into the `Consume`-function to avoid deadlocks if one of the processor-callbacks actually uses an `Emitter` instead of calling `ctx.Emit`.
But that's an issue we have to test a bit more, maybe the Emitter using the `Consume`-function would not actually cause a deadlock and if it does, maybe the Emitter should have an option to mark it as internal. 
I think I need some time to come up with a solution. But you're very welcome to contribute if you got some time :).

**Comment by activeshadow** [comment]
Thank you for the reply @frairon. I'm assuming the PR you created, then deleted w/out merging, causes deadlocks in tests? Regardless, I'll take a look at the code you added in the deleted PR to see what your thoughts were and see if I can't come up w/ a contribution as well.

**Comment by frairon** [comment]
@activeshadow, well in the PR my idea was to give you a quick workaround (like a flush-function in the tester) that you could use in your test to get it running until we find a proper solution, but then I realized that this would require you to call that from production code if you're in test, which is probably not what you want :).
But if you're fine doing the `Flush` in the test only we could also leave that in the branch and you just vendor the branch until we fix it.

**Comment by activeshadow** [comment]
I added the `tester.Flush()` method to a local copy of `goka` and my tests now pass. I'm assuming, however, based on your original comment above, that this might deadlock/break tests if callbacks passed to Goka Processors use an Emitter to emit messages instead of using the `context.Emit` function. Is it common for Processors to use Emitters instead of the context for emitting messages? If so, what's the advantage? Would deadlocks occur if the `tester.Flush()` method is not called in the test code?

Regarding your most recent comment, I'm not seeing why/how I would have to call the `tester.Flush()` function from production code, especially since I only have a `tester.Tester` available to me in my test code. Can you elaborate?

**Comment by frairon** [comment]
It's not common at all to use a separate emitter inside a processor. The only use case I can imagine is when a processor should emit into a separated kafka cluster, which wouldn't be reachable via the context. So changing the emitter would break tests like tihs.
However, what I'm also not sure of is that it would actually deadlock, just assuming. So I guess this  should be the first thing to test. If there's no dead lock we can simply go that route, if not, maybe provide a workaround for this edgecase instead of the workaround for the normal use case.

Why I didn't want to have the Flush as a workaround is that I assumed this Flush would have to be put next to the code calling the Emit (so in production code). But you're right, if we call the Flush somewhere in the unit-test it's fine as a workaround, but not optimal since it's an extra call that has to be added for the test to run. 
So if you're fine with the workaround in your copy, let's leave it and I'll try to implement the real solution soonish.

**Comment by activeshadow** [comment]
@frairon I'm fine w/ just leaving the `tester.Flush()` workaround in my local copy.

I'd love to take a stab at testing whether or not changing the emitter would cause a deadlock, but I'll be honest... I'm not seeing where to make that change. From what I can tell, an emitter created using the `WithEmitterTester` option ends up calling the `tester.pushMessage` function ([see here](https://github.com/lovoo/goka/blob/6636bb3e45be7274659cf3264e3c76415540900e/tester/tester.go#L304)) when `emitter.Emit` is called, just like the `tester.Consume` function does ([see here](https://github.com/lovoo/goka/blob/6636bb3e45be7274659cf3264e3c76415540900e/tester/tester.go#L282)).

**Comment by frairon** [comment]
@activeshadow Next try [here](https://github.com/lovoo/goka/pull/190). This makes the emitter flush after emitting by wrapping the producer.
This works however only if the tester is not used inside a processor callback. Otherwise it will deadlock. I added a unit-test for this case. 
Thanks for checking the code anyway! Just thought it would be easier if I'd just add that quickly :).
Let me know what you think.

**Comment by activeshadow** [comment]
Thanks @frairon! I'll check out this branch, get my tests working w/ it, and see if I can make it deadlock by removing the separate tester from your unit test that's used for the emitter inside the producer.

More to come. Thanks again!

**Comment by activeshadow** [comment]
@frairon my tests now pass (w/out the need for `tester.Flush()`) and I did confirm the deadlock when the same tester is used for both the emitter and the processor that uses the emitter.

Thanks again!

**Comment by frairon** [comment]
Hi @activeshadow no problem, glad your problem could be solved and someone is using the Tester :)

**Comment by activeshadow** [comment]
Do you think this will be something that gets merged into the main code base @frairon?

**Comment by frairon** [comment]
already done, just needed to wait for an approval :). It's in version v0.1.2
