### ISSUE TITLE
What's the best approach for iterating a table in a processor?

### ISSUE THREAD

**Issue by activeshadow** [lovoo/goka#191]
I have a use case that's similar to the [filtering of blocked users in Example 3](https://github.com/lovoo/goka/tree/master/examples/3-messaging#filter-messages-from-blocked-users-with-contextjoin). My use case, though, involves filtering against wildcard entries, so doing a join doesn't work.

Ultimately I need to compare a given value against all the wildcards in the table until a match is found (or I reach the end). I'm not seeing how it's possible to iterate over table value within a processor handler, and even if it were possible I'm thinking it would be a bad idea performance-wise.

An idea I had was to use a view to iterate the table and create an array of wildcards when I'm starting the filter processor, and have the stream that new wildcards get added to as an additional input to the filter processor so it would get updated while running (ie. only iterate the view once at startup). Is this a valid approach? Is it even possible to have two inputs to a processor? If so, are there performance/configuration issues to worry about?

Is there a better way that I'm overlooking?

Lastly, are GitHub issues the correct medium for asking questions like this, or would it be better for me to ask them somewhere else?

**Comment by db7** [comment]
> Lastly, are GitHub issues the correct medium for asking questions like this, or would it be better for me to ask them somewhere else?

Sure, GitHub issues are fine since the community is rather small. If you like there is also a goka channel in the gophers.slack.

> I need to compare a given value against all the wildcards in the table until a match is found (or I reach the end). I'm not seeing how it's possible to iterate over table value within a processor handler, and even if it were possible I'm thinking it would be a bad idea performance-wise.

You are right, joining is not the right approach here. Currently, the only way to be able to iterate over a view is to pass a view object to the ProcessorCallback. But as you can imagine, if you iterate over the view for each and every event, you'll be doing multiple disk seeks per event, and that will hurt your performance. I wouldn't use iteration, but if you want to, two things could help improve performance:
- If your match-table is small you could wrap the view and keep it in memory (see [notes here](https://github.com/lovoo/goka/wiki/Tips#adding-an-lru-cache-around-the-local-storage))
- If you can use prefix-based matches, then you can use range queries in the views to reduce the iteration length.

> An idea I had was to use a view to iterate the table and create an array of wildcards when I'm starting the filter processor, and have the stream that new wildcards get added to as an additional input to the filter processor so it would get updated while running (ie. only iterate the view once at startup). Is this a valid approach? Is it even possible to have two inputs to a processor? 

Sounds pretty good. Views are just the most basic index one can have. In the past, I've used other in-memory data structures to do quick searches, depending on the task r-trees, bloom filters, etc.

Now, regarding your approach, if you use the processor to consume the updates that could cause lost updates or inconsistencies. If that is problem for you, then the best approach is to use the UpdateCallback of the view, but it requires bit of work.

I suggest the following:
- create a thread-safe in-memory data structure that can perform your match task efficiently
- once you start the program, iterate over the whole view and populate the initial data structure (*)
- use the update callback to update the data structure -- whenever an update to the view arrives, you also update your data structure
- pass the view to the processor callback

(*) How large is your matche-table, few MB or many GB? Can you afford reading it completely from Kafka every time you start your program?

**Comment by activeshadow** [comment]
>     I need to compare a given value against all the wildcards in the table
>     until a match is found (or I reach the end). I'm not seeing how it's
>     possible to iterate over table value within a processor handler, and even
>     if it were possible I'm thinking it would be a bad idea performance-wise.
> 
> You are right, joining is not the right approach here. Currently, the only way
> to be able to iterate over a view is to pass a view object to the
> ProcessorCallback. But as you can imagine, if you iterate over the view for
> each and every event, you'll be doing multiple disk seeks per event, and that
> will hurt your performance. I wouldn't use iteration, but if you want to, two
> things could help improve performance:
> 
>   • If your match-table is small you could wrap the view and keep it in memory
>     (see notes here)

The table will be small relative to the amount of data being processed
by the stream.

>   • If you can use prefix-based matches, then you can use range queries in the
>     views to reduce the iteration length.

This sounds interesting, but it's not just prefix matches we're doing...
the wildcard can be anywhere and can appear multiple times.

>     An idea I had was to use a view to iterate the table and create an array of
>     wildcards when I'm starting the filter processor, and have the stream that
>     new wildcards get added to as an additional input to the filter processor
>     so it would get updated while running (ie. only iterate the view once at
>     startup). Is this a valid approach? Is it even possible to have two inputs
>     to a processor?
> 
> Sounds pretty good. Views are just the most basic index one can have. In the
> past, I've used other in-memory data structures to do quick searches, depending
> on the task r-trees, bloom filters, etc.

And you do this in a similar fashion to the LRU cache example, where you
implement a custom storage provider that gets used by a view?

> Now, regarding your approach, if you use the processor to consume the updates
> that could cause lost updates or inconsistencies. If that is problem for you,
> then the best approach is to use the UpdateCallback of the view, but it
> requires bit of work.

Can you elaborate on the possibility of lost updates or inconsistencies?
Is this due to more than one input into the processor, or due to
something else?

> I suggest the following:
> 
>   • create a thread-safe in-memory data structure that can perform your match
>     task efficiently
>   • once you start the program, iterate over the whole view and populate the
>     initial data structure (*)
>   • use the update callback to update the data structure -- whenever an update
>     to the view arrives, you also update your data structure
>   • pass the view to the processor callback

Thank you for the suggestion! I was not aware of the view callback. Is
there a reason you're suggesting passing the view to the processor
callback? What about just passing the in-memory data structure the view
updates to the processor callback? Assuming the in-memory data structure
was used as a custom storage provider to the view, then passing the view
would be required, but off the top of my head it sounds like using the
view callback would allow the in-memory data structure to be
all-together separate from the view.

> (*) How large is your matche-table, few MB or many GB? Can you afford reading
> it completely from Kafka every time you start your program?

The match table will be relatively small. I think it's safe to assume it
would be in the few MB range.

**Comment by db7** [comment]
>Can you elaborate on the possibility of lost updates or inconsistencies? Is this due to more than one input into the processor, or due to something else?

Processors use consumer groups. So they store consumed offsets in Kafka. Views keep in local storage the offset (they don't use consumer groups). I think it is a bit hard to keep them in sync, but maybe I am too cautions. If you try in this way, let me know if it works fine.

> What about just passing the in-memory data structure the view updates to the processor callback?

Sure. No reason to pass the view if you keep the complete values in your array. If your values are too large, you could add to the array only the keys, and if there is a match you read from the view.

To initialize the data structure, you have to iterate over the view before you start the view, otherwise you could see updates out of order. So first read the current local state, then start consuming the updates.

Something like this:

```go
view, _ := goka.NewView(brokers, table, new(codec.String),
	goka.WithViewCallback(
		func(s storage.Storage, partition int32, key string, value []byte) error {
			// update data structure
			updateDS(key, value)

			// call the default update to store in the local storage
			return goka.DefaultUpdate(s, partition, key, value)
		}),
)

// iterate over view and intialize data structure before consuming new events
initializeDS(view)

// start consuming new events
go view.Run(ctx)
```

Take a look at this [gist](https://gist.github.com/db7/38791842583c0eabde523191521a64fc) and let me know if it helps.

**Comment by activeshadow** [comment]
Awesome, thank you @db7. This is pretty much the approach I implemented after reading your first response yesterday, but I totally missed the need for the call to `goka.DefaultUpdate`.
