### ISSUE TITLE
[Question] Prevent commit offset with errors not in messages callback

### ISSUE THREAD

**Issue by 5cmpersec** [lovoo/goka#193]
We are using `goka` in our data pipeline service, the service consumes from `topic#1`, do some transformations on data, then produce the data to `topic#2`.
the code looks like this:

```golang
cbTopic1 = func(ctx goka.Context, msg interface{}) {
    data := transform(msg)
    ctx.Emit(topic2, ctx.Key(), data)
}

g := goka.DefineGroup(group,
	goka.Input(topic1, new(codec.Bytes), cbTopic1),
	goka.Output(topic2, new(codec.Bytes)),
)
```
how can we prevent commiting offset of `topic#1` in case the data can not be produced to `topic#2` successfully?
Can we simply replace `sarama.AsyncProducer` with `sarama.SyncProducer` by implementing custom `ProducerBuilder`?

Thanks.

**Comment by frairon** [comment]
Hi 5cmpersec,

If `ctx.Emit` fails for some reason, the message will not be committed and the processor will shutdown automatically, so you're safe in this scenario.
However, you cannot continue, because in Kafka, messages are consumed in the order in which they were produced. If you can't process a message for some reason, you have to drop it. Unlike NSQ or PubSub you can't "not acknowledge" a message in order to receive it again some time later.
If you deliberately want to ignore a message "for now" and then process it sometime later or somewhere else, the only thing you can do is forward it "somewhere else", of which the easiest would be another `ctx.Emit` so that it ends up in another topic of Kafka and another processor can process it eventually.

Hope that helps, let me know if I completely misunderstood your question :)

**Comment by 5cmpersec** [comment]
Thank @frairon for your answer.

> If ctx.Emit fails for some reason, the message will not be committed and the processor will shutdown automatically, so you're safe in this scenario.

as I understand, `ctx.Emit` is asynchronous, `ctx.Emit` returns (no fail) doesn't mean that the data is sent to Kafka successfully. So there is a chance that `topic#1`'s offset is committed before the processor shut down, leading to a unexpected situation: for example `msg1` of `topic#1` is committed but the tranformed data of msg1 never reach `topic#2`

> However, you cannot continue

We can continue in case the message is OK and problem is at Kafka server such as network temporary down, wrong settings, etc. In this case, we expect that after processor restarts it will consume the message (`msg1` for example) again.
However, if the offset of `msg1` is committed before the processor restarts, then it will never be consumed except manually seeking the offset.

**Comment by frairon** [comment]
Hi @5cmpersec,

you're right `ctx.Emit` works asynchronously so that it returns even if when sending the message will fail. 
However, committing the message works asynchronously as well, so if sending the message fails, the input message will not be committed. 
Since messages are consumed in order and produced in order, they'll also be committed in order, meaning you'll not lose the message if the producer fails. @db7 please correct me if I'm wrong here. 

If you do experience messages being lost after emitting errors, feel free to write a test or some code that triggers that behavior, because this would be a bug I think.

**Comment by db7** [comment]
That's right -- at least that is the intention.

Each input message of the processor gets a `goka.Context` object. The offset of the input message is only committed once all side effects issued by the context interface have finished. That can happen after the process callback has finished.

**Comment by db7** [comment]
@5cmpersec I assume this question is answered. Reopen if necessary.
