### ISSUE TITLE
Question: Access to the Iterator in a Join

### ISSUE THREAD

**Issue by gmather** [lovoo/goka#275]
We have a use case where we'd want access to the underlying Iterator inside a Join callback. Currently the `Context` can access the value at the same key as the input. It's not a large change to get access to the iterator but it does involve a new method on `Context`. 

My question is whether you would be receptive to Pull Requests for changes like this. I realize it's likely a niche use case and is technically a breaking change. I can elaborate on the usecase on the PR if it's something you'd consider.

Thanks.

**Comment by frairon** [comment]
Hi @gmather, that's quite an interesting proposal, and we never had the requirement honestly that's why it was never considered.

Important to note though: iterating would require a Lookup instead of a Join, as the Join might not be the full View if the group has multiple instances and the partitions are separated between processes. 

Apart from that I don't see a reason why the Context shouldn't provide a function like `Iterate(table Table)` similar to the `Lookup(key string)` method. After all they'd use the same underlying view.
One thing to keep in mind: the iterator should be closed when the callback returns, so maybe all iterators could be stored in a list in the context and be cleaned up when finishing the context to avoid leaks if the callback does not close them properly.
So feel free to give it a try, I'm happy to review a PR on that. 

Thanks a lot!

**Comment by frairon** [comment]
Inactive for a year now, I'll close it. Feel free to reopen if you see any need for action.
