### ISSUE TITLE
Is it possible to add the function of grouping by fields

### ISSUE THREAD

**Issue by Greyh4t** [lovoo/goka#299]
There is a fieldsGrouping feature in storm that sends messages with the same fields to the same machine, is it possible to add a feature like this

**Comment by R053NR07** [comment]
Hey @Greyh4t,
I'm not sure if I understand your use case completely but I'll try to make my points clear. So since we don't use Storm I'm not really sure where you want this feature to be placed. Generally there are two completely separate options:

1. For processor
2. For the views

When it comes to 1. the implementation of such feature is not trivial since kafka splits the workload internally among the processors (consumers) in respect to their keys. This means to partition the data based on some fields you would need to have multiple processors consuming from different topics. And some kind of input processor splitting the workload based on the fieldsGrouping. I can't see a general way of providing such behavior in some goka way; which means you have to build this for your own.

Regarding 2. there would be some ways built in for dropping data not belonging into the view. So if you want to have specific data in specific services having the view on a processor table you can do that by using `goka.ViewOptions` specifically `goka.WithViewCallback`. There you could specify a callback which is executed on every view update so you could decode your data and filter specific groups. This would result in a view providing filtered data.

Does this make sense and is it actually what you wanted to achieve?

**Comment by Greyh4t** [comment]
Hi, thanks for your patient reply!

This feature should be for processors.

The actual business requirement is like this:
Each message in kafka is a url, we need to calculate the statistics for the url with the same domain name, and in the case of distributed deployment, the url with the same domain name is sent to the same server to ensure that the statistics are accurate

**Comment by R053NR07** [comment]
And the purpose of the processor would be just to aggregate this count/statistics?

If that's the case you can use a `goka.Loop` in your processor. Then you could consume from some input stream with arbitrary key, analyze the data and loopback with the domain as key. In the loopback you can then do the calculations you want to do and persist the result. This would lead to a processor which maps domains as key to the stats. You can have a look at [example-3](https://github.com/lovoo/goka/tree/master/examples/3-messaging) there are the loopbacks used. If that's not what you want (e.g. the keys are then the domains but some other key) it sounds rather like you need a second processor doing the job for you. 

So it really depends on what data you are actually processing and what exact goal you are trying to achieve. In general I would say there are already multiple ways of doing such a thing with goka. It just depends on what the processor should do in the end and what you want to solve. If you just want to have a mapping from domain -> counter I guess the proposal is sufficient. If your processor should do other stuff in the first place and this mapping is just a secondary need I would write another processor and emit to this one during the processing in the first one (by defining an output in the group graph and doing ctx.Emit during the processing). Then you would have a mapping from somekey -> somedata and in a second Table domain -> counter.

**Comment by Greyh4t** [comment]
The previous mentioned is a simplified requirement, our actual requirement is :
Read the url in kafka, extract the domain and path part of the url, perform statistics on the path part of the same domain, generate rules based on the statistics (these rules are used to match similar urls), put the rules into memory, and apply the rules to find similar urls when processing new urls. because of the large amount of data, it needs to be distributed deployment, according to the example you said, if we can make sure that the statistics are calculated according to the domain name in the distributed case, and the generated rules are shared globally, it seems to achieve our needs, I will study it, thanks a lot.

**Comment by Greyh4t** [comment]
![flow](https://user-images.githubusercontent.com/8017380/107853341-39bc1a80-6e50-11eb-95e8-c66ed737e9d4.png)
This is the actual flow chart.
A rule list can be simply understood as a map, where the key is the domain, and the value is the specific rule
{
    "www.a.com": ["rule_a1", "rule_a2"],
    "www.b.com": ["rule_b1", "rule_b2"]
}

**Comment by R053NR07** [comment]
No problem. Just check it out and if you have further questions just come back :)
