### ISSUE TITLE
Support batch producing for Emitter

### ISSUE THREAD

**Issue by danchupin** [lovoo/goka#311]
Why Emitter does not support batch producing?
In some cases batch producing can significantly improve write performance over single message write.

**Comment by frairon** [comment]
Hey @danchupin, the emitter batches internally, it uses sarama.`AsyncProducer` internally that does the batching.
Thats why, if you call `Emit`, it returns a promise that lets you handle the success/failure of emitting the message via callback (because it's being batched).
Does that answer your question?

**Comment by danchupin** [comment]
Yes, thanks :)
