### ISSUE TITLE
Lookup's possibly not fast enough when building streaming sessions

### ISSUE THREAD

**Issue by mikedewar** [lovoo/goka#335]
I'd like to be able to build sessions in a streaming manner, turning a stream of events into a stream of arrays, where each array is composed of events concatenated together based on some rule. Aside from one little wrinkle, Goka makes this a very pleasurable experience, so thanks for that! 

The way I've implemented it is that there are two processors. The first has an input, an output, and a lookup edge. The lookup edge points at the second processor, which itself has an input and a persist edge. 

The first processor, upon receiving a keyed message, looks up the key from the state of the second processor using `ctx.Lookup("secondProcessor", ctx.Key())`. This will retrieve an array of events, to which the first processor will append the current event and then emit the updated array . 

The second processor listens to this topic of arrays, persisting them using `ctx.SetValue(msg)`.

It works great until messages arrive at the first processor faster than the mechanism behind `ctx.SetValue(msg)` can make the update state available via `ctx.Lookup`. When the second message arrives at the first processor, my ctx.Lookup returns an array that doesn't contain the first event that arrived just a moment before because the state update in the second processor is not complete. In this case, I'll append the second message to the array, without the first message, emit it, and the second processor will overwrite its state with this new array, losing the first message. 

I understand why this happens (and a recent question from oss92 and the resulting conversation has made this very clear) but what I'm less sure is what to do about it. 

The first option I've looked at is to create my own mechanism, giving the first processor the chance to be blocked by writes that aren't complete yet, but it's clumsy at best and involves polling a view to find out whether or not the Lookup has been updated yet. This has felt like a rabbit hole, and also that maybe I've misunderstood something about the patterns that Goka encourages. 

I appreciate I can replace `ctx.Lookup("secondProcessor", ctx.Key())` with `ctx.Join("secondProcessor")` (which is lovely) but I don't think that solves the issue, in that I'm still possibly going to get the state before the write has completed.  

I was hoping that maybe the `Loop` edge type might help? Or that I'm missing some sort of write receipt or some other mechanism - or maybe even a different pattern? Would love any thoughts!

In case it's handy, my little toy app is here https://github.com/mikedewar/aggregator - this uses the above pattern, though doesn't include any attempts to solve the race.

**Comment by frairon** [comment]
Hi @mikedewar,

thanks for creating that issue, it clearly shows there's a lack of documentation/examples on how to use the Edges and some classic use case examples.

Regarding the aggregation problem. The solution is pretty simple: instead of reading from a lookup table, the writing processor must read its own table and store back the value. The view is only used for reading (e.g. to be served via web). Never use the value from a view of the processor-table to modify the table value. Otherwise you will inevitably run into the described race condition. 

This is how it could done: https://github.com/mikedewar/aggregator/compare/master...frairon:master
(don't mind the go-mod stuff)
* appender is not necessary, the windowState processor does the aggregation, so I moved the topics and the callback logic there.
* next to updating state, it also pushes the current session into a stream that the next processor in the pipeline (featureBuilder) consumes and converts into features. `featureBuilder` could in fact also consume the updates of the windowState-table, but let's keep it clean and avoid such hacks :)
* No need to create the partition-table manually. Possibly avoid it, the processor will do it. All topics need to be copartitioned. A processor only works if both all input topics and the table-topic have the same number of partitions. In the example, input topics had 1 partition and the table had 10 - this will lead to inconsistent results.
* style-note: a topic, should always use a single codec. The example uses both `arrayCodec` and `btreeCodec` for topic "sessions", because the arrayCodec unmarshals first the btree and then converts it into an array. However, this should be done on application level. So we should only use btreeCodec and if the consume wants to convert it to something different, then do it in the consume function. It's not wrong or an error the way it's currently implemented, just found it very confusing to figure out what's actually stored in the topic.
* a join wouldn't have solved the issue, because it's essentially a lookup where the key is `ctx.Key()`

Some background how Goka works: Consider a normal database application. If we read one entry, modify it and write it back concurrently, we will experience lost-updates eventually. To solve it, we would use transactions, so if two processes modify the same entry, one will retry. 
In Goka however, there are no transactions and no race conditions, because messages - which are in the end "requests" to change the value for specific keys - are serialized by Kafka through topics and partitions. A goka processor executes one goroutine per partition. If there are multiple input topics, then all messages are serialized internally into a channel into that one goroutine. That means, inside the processor callback, we are guaranteed, that `ctx.Value()` returns the same value that was stored by a previous call to `ctx.SetValue(..)` **for the same key in the same partition**, because there is no concurrency and nothing else is modify that value. Any lookups/joins/view-get's on the same table that is being modified will actually create those race conditions and must be avoided.

As pointed out in the recent issue reported by oss92, it is crucial that the incoming partition matches the partition that goka assumes, otherwise `ctx.Value()` will not be what was written last by `ctx.SetValue(..)`. 
The example project uses a goka-emitter though, so no worries about that. Just want to point out that it might become an issue, if you don't have control over the emitter where the processor consumes events from.

Hope this is helpful to you.

**Comment by mikedewar** [comment]
This is brilliant, thankyou so much. 

I think my core issue is that for whatever reason I was stuck on the idea that a table had to reflect the input topic. So doing anything other than `ctx.SetValue(msg)` was discouraged. 

In your response, the specific bit that unblocked my brain was in the comment in the diff:

```
// emit the new, ordered window
ctx.SetValue(window)
```

until I read that, the idea that `SetValue` was actually an emission - which I understood from a mechanical perspective thanks to reading the documentation and posts etc - but I hadn't internalised it properly as a library user; the fact that `ctx.SetValue` is an emission and you guys are taking care of that part of the pattern had simply not landed. I've been taking it as my responsibility to do the emission using `ctx.Emit` which in turn made me stuck on the idea that I should only ever really do `ctx.SetValue(msg)`.

I appreciate this might be an idiosyncratic mental block, so not sure it's really a deficiency in the documentation! If I can get my little windowed feature builder into an acceptable state I'd love to contribute it to the examples, if in fact it's a distinct use case you haven't covered already.

**Comment by frairon** [comment]
closing, seems to be answered
