### ISSUE TITLE
recovery takes too long

### ISSUE THREAD

**Issue by andronux** [lovoo/goka#347]
Hello,

what would be the leverage for increasing recovery time?

We're using a local storage (emptyDir) and it takes about 40min (for about 120k messages in the topic) to do the recovery and consumes a high bandwidth:

![image](https://user-images.githubusercontent.com/31890696/133821751-153696f0-5b0b-4ed9-9409-e930489acf5b.png)

Will redis help here?

**Comment by db7** [comment]
If the storage is initially empty, it will recover the whole topic. Be sure that the topic is configured with cleanup.policy=compact, otherwise LevelDB will take longer because it will need to clean up all overwrites to the same keys. Also, you could use persistent disks, so that once it recovers/restarts, you don't have to consume the whole topic, but only the newest updates.

**Comment by andronux** [comment]
Hello @db7 ,

thank you very much for your quick reply.

in a context of k8s, you would recommend use statefulset instead of simple deployment? 

How about using redis as backend/cache?

**Comment by frairon** [comment]
Hi @andronux,

yes it is recommended to avoid full recovery on every restart, as this will use lots of bandwidth and memory - so it takes a while depending on the amount of data. Statefulsets are the way to go on kubernetes.
If you're using multiple pods it is also recommended to use the options hot-standby and recover-ahead. Otherwise every rebalance/redeploy might take a lot of time as the pods will recover the partitions they haven't been assigned to in the previous run. (see https://pkg.go.dev/github.com/lovoo/goka@v1.1.0-beta.0#WithHotStandby. it's still in beta-release, but will be released to v1.1.0 soonish)

Regarding redis: in terms of speed, we have had best results with leveldb. Maybe there are other local key-value store implementations that perform similar or even better. Using redis only makes sense if you intend to read the data stored by goka with another client, right? 
Unless the table is very small. But in this case you can either use memory-storage or just recovery the whole table on every start.

For your specific use case: are the 120k messages in the group table quite big? If so, it looks like bandwidth is your biggest problem when doing full-recovery. Then the type of backend isn't too important, so using stateful sets might already solve the issue.
In our systems, messages are usually quite small and recovering 120k messages would be a matter of seconds or couple of minutes, so I was wondering why it would take that long in the first place.

**Comment by frairon** [comment]
closing it, seems to be answered
