### ISSUE TITLE
Question: Regarding Emitters Connection

### ISSUE THREAD

**Issue by fahmyabdul** [lovoo/goka#399]
So I've been trying Goka these past few days, I used to use plain Sarama at my previous company, but my new company prefer to use Goka over plain Sarama. I'm still not familiar with Goka's concept. So pardon me if my question is confusing or not relevant.

One of the things that I'm not quite sure in Goka is about emitters. Usually using plain Sarama I just have to create a producer connection once and then every single function just have to use that connection when publishing message and then the connection will be closed when the application/service closed. 
But with Goka I see that Emitters can only use one topic during goka.NewEmitter() call and if I want to publish to different topic that means I have to call goka.NewEmitter() again, which means it will create new connection every single time right? 
Wont that affect performance? Isn't opening the connection once for all publish better than opening new connection for every publish? Is there a way to do that? Or is it intended to be like that, one topic per emitter?

I'm sorry if my English a bit rough, and if this question already answered/explained before. 

Thanks.

**Comment by frairon** [comment]
Hi @fahmyabdul,
first, you're right about needing one emitter per topic. The reason for this is that goka builds around the idea that all messages in a topic have the same type, i.e. share a `Codec`. That's why you need to specify the codec when building an Emitter.
Second reason is, that topics are usually more or less static and one does not need to publish to many of them dynamically from a single application.

If you do need to emit to different topics from one point, create a map that holds all emitters and create them if they're required.
So generally you're right, one should not create a single emitter for every message, that would be really unperformant. Better create an emitter if you need one and close it at application shutdown.

Since the Emit-method needs an object, one could do the selection of the emitter via topic-name or reflection (if you can live with the performance impact). We use that approach on different occations, usually for setting up data in a cluster for integration testing. I'm happy to give you some example code, if you need.

At the end of the day, if you don't care about types (i.e. use the Bytes-codec), there's also no harm using a plain sarama-producer. Just make sure the partitioning is the same, otherwise goka will store the messages in different partitions than sarama, which will break your data for sure.

Hope that helps!

**Comment by fahmyabdul** [comment]
I see, I just did the same as what you said, I created a map to holds all the emitters and closed it when the application terminated.

I'm still trying to figure out the best use case of goka for my application. There're still a lot to learn about goka moving from plain Sarama.

Thanks for the explanations, it helps a lot!
