### ISSUE TITLE
What storage I should use for processor and view?

### ISSUE THREAD

**Issue by korrawit** [lovoo/goka#424]
Hello,

What is the use case for using remote storage for processor and view? Should I leave it as default (LevelDB)?

Thanks,

**Comment by frairon** [comment]
Hey there, 

with "remote storage" you mean redis?
I think the only reason for doing that is if you wanted to access the data from another client. We don't use this method in production to be honest, because usually when you need a special kind of storage, you'll also need to transform it - so replacing the bare storage is not too helpful.
So for almost all cases leveldb is fine.

Franz

**Comment by korrawit** [comment]
@frairon Yes, I mean redis.

Got it.

Currently, I'm running Goka Processor and Goka view on the K8s cluster and it is written in `/tmp` folder. 
Do you think that's a proper setup? or any concerns?

Thanks,

**Comment by frairon** [comment]
Hey @korrawit ,

very sorry for the late response!

>Currently, I'm running Goka Processor and Goka view on the K8s cluster and it is written in /tmp folder.
Do you think that's a proper setup? or any concerns?

usually we keep our data on a persistent disk, because recovering everything from scratch would be too slow (usually  a table has  more than 50million entries). 
If the tables are super-small (e.g. we use them to store configuration), then it's fine to recover them from scratch every time.
So our kubernetes setup means roughly:

* type: statefulset
* no autoscaling
* persistent volume claim mounted to the pod.

Hope that helps!

**Comment by frairon** [comment]
closing this, feel free to reopen if there are new issues
