### ISSUE TITLE
HowToX : Is it possible to iterate on View with a subset ? 

### ISSUE THREAD

**Issue by jbpin** [lovoo/goka#82]
Hi, 
All is in the title.. I want to iterate on the view for a subset of key as with syndtr/goleveldb
 ```
iter := db.NewIterator(util.BytesPrefix([]byte("foo-")), nil)
for iter.Next() {
	// Use key/value.
	...
}
iter.Release()
err = iter.Error()
```

Can you give me some direction please ? I'm also keen to manage a PR for that if necessary.

**Comment by db7** [comment]
The View iterator would does not provide that. But if you want to implement that, go ahead. You'll find the iterator implementation inside `storage`. You can combine the iterators of each partition (since each partition is a DB) with the multi iterator, also defined in the storage package. Let me know if you need some help.

**Comment by db7** [comment]
Thanks for contributing. I'll close this issue since your PR #85 resolves it.

**Comment by jbpin** [comment]
You are welcome.. appreciate.
