### ISSUE TITLE
Questions about join semantics

### ISSUE THREAD

**Issue by burdiyan** [lovoo/goka#86]
In the blog post announcing Goka (https://tech.lovoo.com/2017/05/23/goka/) author says about some usages of Goka at Lovoo and says there'll be future posts about that. 

There are no more posts about it yet, but I would like to understand the differences between these two joins mentioned in the post:

- key-wise stream-table joins, e.g., joining user actions with user profiles;
- cross-joins/broadcast-joins, e.g., joining user actions with a device table;

I think the second one is what I need for my use case, but it's not clear to me how to implement it.

I'll describe the use case:

We have a compacted topic of users and compacted topic of bookings. Users are partitioned by user id, and bookings are partitioned by booking id. We create a group table for basic user data and a counter for all the bookings per user.

We've tried several approaches so far:

1. Loopback topic:

- We create a group with input of users topic and input of bookings topic.
- Users callback sets the value in the group table with basic user data.
- Bookings callback sends booking data to a loopback topic with user id as key, so that bookings and users are now partitioned by the same user id.
- Loopback topic processor gets user data from group state, and increment a counter for bookings.

The issue with this approach is that we could have duplicated bookings because of "at least once" semantics. But we need accurate data.

2. Joins:

- We do the same as before, but instead of sending bookings to the loop topic, we emit them to a normal topic.
- Then in users callback we do `ctx.Join` with this repartitioned bookings topic.

The problem with this one is that we loose most of the bookings, since it's not guaranteed that we've processed all bookings for a given user, before message on users topic is processed for a particular user.

It sounds like cross-joins/broadcast-joins is what we actually need, but I'm not sure.

In Kafka Streams semantics what we need I believe would be KTable-KTable join.

What would you recommend to solve this situation?

**Comment by db7** [comment]
When consuming a stream, you can enrich the stream by joining it with tables using `ctx.Join` or `ctx.Lookup`, for example, an event "user-logged-in" arrives; you lookup a device-table using the device id in the user-logged-in event and combine the device information with the event. The result can be emitted downstream or stored in a group table. So this is a Stream-Table join. The callbacks will be triggered by the stream and you'll see all events from the stream. The joined tables are passive, they will be kept up-to-date, but you typically don't get triggered for their updates (unless you use `UpdateCallback`).

In your case, you want to count how many bookings a user has performed. I would do something similar to your approaches, but I would not pack user and booking in the same processor. I'd have one processor for the booking-table and one processor for the user-table. The booking processor would emit into a topic "user-booked-stream" using the user as key. The user processor would consume (with multiple callbacks) from the user streams plus this "user-booked-stream".

The at least once issue would have to be solved by keeping a set of bookings of the user instead of simply counting them. Does that help you further?

**Comment by burdiyan** [comment]
@db7

To do exactly once counting, that's exactly what I was thinking about (keeping set of ids instead of a counter, at least during some limited timeframe/window).

Thanks a lot for your recommendations, it helped a lot!
